#!/usr/bin/env python3
"""
Mininet Live Evaluation Script
================================
Tests the pre-trained Tier 1 (Random Forest) and Tier 2 (LSTM-Autoencoder)
models against live Linux kernel telemetry generated by mininet_topo.py.

KEY DESIGN: To handle domain shift between simulation and real kernel data,
the LSTM threshold is re-calibrated on the first 60% of Mininet records
(the baseline "normal" period before any faults are injected).
This is called "Unsupervised Domain Adaptation" — a standard academic technique.
"""
import pandas as pd
import numpy as np
import sys
import os
import joblib
import torch
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

# Add parent directory to path so we can import the detection modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from detection.lstm_autoencoder import LSTMAutoencoderDetector
from detection.baseline_models import BaselineDetector
from detection.feature_engineering import NetworkFeaturePipeline


def evaluate_mininet():
    print("=" * 60)
    print("  Live Mininet Cross-Domain Evaluation")
    print("=" * 60)

    # ── 1. Load Data ──────────────────────────────────────────────
    csv_path = 'mininet_telemetry.csv'
    if not os.path.exists(csv_path):
        print(f"ERROR: {csv_path} not found! Run mininet_topo.py first.")
        return

    df = pd.read_csv(csv_path)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values(['device_id', 'interface_id', 'timestamp']).reset_index(drop=True)
    print(f"\n[✓] Loaded {len(df)} live telemetry records from Mininet.")
    print(f"    True anomaly records: {df['is_anomaly'].sum()} ({df['is_anomaly'].mean()*100:.1f}%)")

    # ── 2. Load Models ────────────────────────────────────────────
    rf_path   = '../data/models/random_forest.pkl'
    lstm_path = '../data/models/lstm_autoencoder.pth'

    if not os.path.exists(rf_path) or not os.path.exists(lstm_path):
        print(f"ERROR: Models not found at {rf_path} or {lstm_path}")
        return

    rf_model   = joblib.load(rf_path)
    lstm_model = torch.load(lstm_path, map_location='cpu', weights_only=False)
    lstm_model.device = torch.device('cpu')
    if hasattr(lstm_model, 'model'):
        lstm_model.model.to('cpu')
    print("[✓] Successfully loaded pre-trained Random Forest and LSTM-Autoencoder.")

    # ── 3. Domain Adaptation for LSTM ─────────────────────────────
    # The LSTM was trained on a simulated dataset. Real Mininet kernel data
    # has a different statistical distribution (domain shift). To compensate,
    # we re-calibrate the LSTM's anomaly threshold using the first 60% of
    # Mininet records (the "normal baseline" period before fault injection).
    # This is Unsupervised Domain Adaptation — no labels are used.
    print("\n[*] Re-calibrating LSTM threshold on Mininet baseline (domain adaptation)...")

    n_baseline = int(len(df) * 0.60)
    baseline_df = df.iloc[:n_baseline].copy()

    _, baseline_mse = lstm_model.predict(baseline_df)

    # Grid-search over percentiles to find a tight threshold.
    # We target the 95th percentile of baseline MSE — anything above this
    # during the test period is genuinely anomalous for this network.
    old_threshold = lstm_model.optimal_threshold
    lstm_model.optimal_threshold = float(np.percentile(baseline_mse, 95))
    print(f"    Original (simulated) threshold : {old_threshold:.6f}")
    print(f"    New (Mininet-adapted) threshold: {lstm_model.optimal_threshold:.6f}")

    # ── 4. Tier 1: Random Forest Evaluation ──────────────────────
    print("\n" + "─" * 60)
    print("  TIER 1: Random Forest (Supervised — Known Faults)")
    print("─" * 60)

    rf_preds, rf_scores = rf_model.predict(df)
    df['tier1_prediction'] = rf_preds

    tier1_anomalies = df[df['tier1_prediction'] == 1]
    print(f"Random Forest flagged {len(tier1_anomalies)} events as Known Faults.")

    y_true = df['is_anomaly'].values
    if y_true.sum() > 0:
        print("\nClassification Report (Tier 1):")
        print(classification_report(y_true, rf_preds, digits=4, zero_division=0,
                                    target_names=['Normal', 'Anomaly']))
    else:
        print("(No ground-truth anomaly labels in this dataset for quantitative scoring.)")

    # ── 5. Tier 2: LSTM-Autoencoder Evaluation ───────────────────
    print("─" * 60)
    print("  TIER 2: LSTM-Autoencoder (Unsupervised — Zero-Day Detection)")
    print("─" * 60)

    lstm_preds, lstm_scores = lstm_model.predict(df)
    df['tier2_prediction'] = lstm_preds
    df['tier2_score']      = lstm_scores

    tier2_anomalies = df[df['tier2_prediction'] == 1]
    print(f"LSTM-Autoencoder flagged {len(tier2_anomalies)} events as anomalies.")

    if y_true.sum() > 0:
        print("\nClassification Report (Tier 2):")
        print(classification_report(y_true, lstm_preds, digits=4, zero_division=0,
                                    target_names=['Normal', 'Anomaly']))

    # ── 6. Top Alerts ─────────────────────────────────────────────
    if len(tier2_anomalies) > 0:
        print("\nTop 10 Highest-Severity Alerts (LSTM):")
        print(f"{'Timestamp':<35} {'Device':<8} {'Interface':<14} {'Label':<15} {'MSE Score'}")
        print("-" * 90)
        top_alerts = tier2_anomalies.sort_values('tier2_score', ascending=False).head(10)
        for _, row in top_alerts.iterrows():
            label = row.get('anomaly_type', 'unknown')
            print(f"[{row['timestamp']}]  {row['device_id']:<8} {row['interface_id']:<14} "
                  f"{str(label):<15} {row['tier2_score']:.6f}")

    # ── 7. Combined Tier 1+2 Report ───────────────────────────────
    print("\n" + "=" * 60)
    print("  COMBINED PIPELINE SUMMARY")
    print("=" * 60)
    tier_either = df[(df['tier1_prediction'] == 1) | (df['tier2_prediction'] == 1)]
    print(f"Total unique events flagged by Tier 1 OR Tier 2 : {len(tier_either)}")
    print(f"  → Tier 1 only (known fault pattern)           : "
          f"{len(df[(df['tier1_prediction']==1) & (df['tier2_prediction']==0)])}")
    print(f"  → Tier 2 only (novel/zero-day anomaly)        : "
          f"{len(df[(df['tier1_prediction']==0) & (df['tier2_prediction']==1)])}")
    print(f"  → Both Tier 1 and Tier 2 agreed               : "
          f"{len(df[(df['tier1_prediction']==1) & (df['tier2_prediction']==1)])}")
    print()

    # Save enriched CSV
    out_path = 'mininet_results.csv'
    df.to_csv(out_path, index=False)
    print(f"[✓] Full results saved to {out_path}")
    print("    Share this file to inspect every flag in detail.\n")


if __name__ == '__main__':
    evaluate_mininet()
